In [104]:
# 导入模块
%matplotlib inline
import torch
import numpy as np
import pylab as pl
from torch import nn
torch.manual_seed(1)
np.random.seed(1)

In [126]:
a = torch.randint(0,20,[3,4,6]).view(3,1,4,6)

In [127]:
w = torch.randint(0,20,[3,2,4]).view(3,1,2,4)

In [128]:
print torch.conv2d(a,w)

tensor([[[[  724.,   890.,  1100.],
          [  964.,  1059.,   762.],
          [  582.,   532.,  1120.]],

         [[  832.,   561.,   673.],
          [  604.,   822.,   765.],
          [  559.,   630.,   587.]],

         [[  793.,   549.,   719.],
          [  645.,   759.,   797.],
          [  418.,   554.,   573.]]],


        [[[  727.,   893.,   638.],
          [  797.,  1025.,  1010.],
          [  613.,   525.,   699.]],

         [[  530.,   666.,   778.],
          [  536.,   733.,   688.],
          [  497.,   564.,   524.]],

         [[  556.,   597.,   755.],
          [  533.,   720.,   771.],
          [  393.,   461.,   460.]]],


        [[[ 1013.,   867.,   884.],
          [  891.,  1209.,  1052.],
          [ 1035.,   744.,   600.]],

         [[  860.,   649.,   790.],
          [  776.,   739.,   826.],
          [  728.,   757.,   496.]],

         [[  833.,   705.,   798.],
          [  743.,   750.,   859.],
          [  723.,   731.,   487.]]]])


In [133]:
class Conv2D(nn.Module):
    def __init__(self, n_channels, kernel_size):
        super(Conv2D, self).__init__()
        self.n_channels = n_channels
        self.kernel_size = kernel_size
        self.W = nn.Parameter(torch.randn(n_channels, *kernel_size))
    def forward(self, x):
        batch_size, n_rows, n_cols = x.size()
        out = []
        for c in range(0, self.n_channels):
            out_c = []
            for i in range(0, n_rows - self.kernel_size[0] + 1):
                for j in range(0, n_cols - self.kernel_size[1] + 1):
                    out_c.append(torch.sum(torch.sum(x[:,i:i + self.kernel_size[0], j:j + self.kernel_size[1]]*self.W[c],-1),-1).unsqueeze(1))
            out_c = torch.cat(out_c,-1).view(-1,1, n_rows - self.kernel_size[0] + 1, n_cols - self.kernel_size[1] + 1)
            out.append(out_c)
        return torch.cat(out,1)

In [145]:
X = torch.FloatTensor([[1,1,1,0,0],[0,1,1,1,0],[0,0,1,1,1],[0,0,1,1,0],[0,1,1,0,0]]).unsqueeze(0)
W = torch.FloatTensor([[1,0,1],[0,1,0],[1,0,1]]).unsqueeze(0)
print('X=\n{}'.format(X))
print('W=\n{}'.format(W))
conv2d = Conv2D(1,(3,3))
conv2d.W.data=W
Y = conv2d(X)
print('Y=\n{}'.format(Y))


X=
tensor([[[ 1.,  1.,  1.,  0.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  0.,  1.,  1.,  1.],
         [ 0.,  0.,  1.,  1.,  0.],
         [ 0.,  1.,  1.,  0.,  0.]]])
W=
tensor([[[ 1.,  0.,  1.],
         [ 0.,  1.,  0.],
         [ 1.,  0.,  1.]]])
Y=
tensor([[[[ 4.,  3.,  4.],
          [ 2.,  4.,  3.],
          [ 2.,  3.,  4.]]]])
torch.Size([1, 1, 3, 3])
tensor([[[[ 4.,  3.,  4.],
          [ 2.,  4.,  3.],
          [ 2.,  3.,  4.]]]])


In [136]:
conv2d.W.data = w.view(3,2,4)
conv2d(a.view(3,4,6))

tensor([[[[  724.,   890.,  1100.],
          [  964.,  1059.,   762.],
          [  582.,   532.,  1120.]],

         [[  832.,   561.,   673.],
          [  604.,   822.,   765.],
          [  559.,   630.,   587.]],

         [[  793.,   549.,   719.],
          [  645.,   759.,   797.],
          [  418.,   554.,   573.]]],


        [[[  727.,   893.,   638.],
          [  797.,  1025.,  1010.],
          [  613.,   525.,   699.]],

         [[  530.,   666.,   778.],
          [  536.,   733.,   688.],
          [  497.,   564.,   524.]],

         [[  556.,   597.,   755.],
          [  533.,   720.,   771.],
          [  393.,   461.,   460.]]],


        [[[ 1013.,   867.,   884.],
          [  891.,  1209.,  1052.],
          [ 1035.,   744.,   600.]],

         [[  860.,   649.,   790.],
          [  776.,   739.,   826.],
          [  728.,   757.,   496.]],

         [[  833.,   705.,   798.],
          [  743.,   750.,   859.],
          [  723.,   731.,   487.]]]])

In [78]:
a.size()

torch.Size([10, 1, 4, 6])